feat: optional replication
mediagis/nominatim-docker pull request #258
Opened 2021-09-15 06:53 UTC by hamid-moghadam

Make "nominatim replication" optional in order to use it in offline servers.
Related to #257

2021-09-15 07:12 UTC, leonardehrenfried commented on 3.7/config.sh
> +if [[ $REPLICATION_UPDATE_INTERVAL =~ $reg_num && "$REPLICATION_URL" != "" ]]; then
Could you add this dependency to the documentation or even better throw an error when an invalid combination was used?

2021-09-15 07:12 UTC, leonardehrenfried requested changes

2021-09-15 07:12 UTC, leonardehrenfried commented on 3.7/config.sh
> +if [[ $REPLICATION_RECHECK_INTERVAL =~ $reg_num && "$REPLICATION_URL" != "" ]]; then
Same here.

2021-09-15 07:13 UTC, leonardehrenfried commented
This looks good - thanks!

@philipkozeny Do you have an opinion on this?

2021-09-15 08:52 UTC, philipkozeny commented
An additional test case without replication would be nice. Can you add that to ```.github/workflows/ci.yml``` please?

2021-11-20 19:03 UTC, leonardehrenfried commented
Superseded by #270

2021-11-20 19:03 UTC, closed without merging